package com.example.kreedaperana.utils

import android.content.Context
import android.content.Intent
import com.example.kreedaperana.data.model.Athlete
import com.example.kreedaperana.data.model.Trial

object ShareUtils {
    fun shareReport(context: Context, athlete: Athlete, trials: List<Trial>) {
        val report = """
            KREEDA PERANA PERFORMANCE REPORT
            --------------------------------
            Athlete: ${athlete.name}
            Sport: ${athlete.primarySport}
            School: ${athlete.school}
            
            Recent Trials:
            ${trials.joinToString("\n") { "- ${it.trialType}: ${it.value}${if (it.trialType == "Sprint") "s" else "m"}" }}
            
            Best Performance: ${trials.maxByOrNull { it.value }?.value ?: 0.0}
            --------------------------------
            Generated by Kreeda-Prerana Scout
        """.trimIndent()

        val sendIntent: Intent = Intent().apply {
            action = Intent.ACTION_SEND
            putExtra(Intent.EXTRA_TEXT, report)
            type = "text/plain"
        }

        val shareIntent = Intent.createChooser(sendIntent, null)
        context.startActivity(shareIntent)
    }

    fun shareSchoolSummary(context: Context, athleteCount: Int, trialCount: Int) {
        val summary = """
            KREEDA PERANA SCHOOL SUMMARY
            ----------------------------
            Total Athletes: $athleteCount
            Total Trials: $trialCount
            Average Trials per Athlete: ${if (athleteCount > 0) trialCount / athleteCount else 0}
            ----------------------------
            Generated by Kreeda-Prerana Scout
        """.trimIndent()

        val sendIntent: Intent = Intent().apply {
            action = Intent.ACTION_SEND
            putExtra(Intent.EXTRA_TEXT, summary)
            type = "text/plain"
        }

        val shareIntent = Intent.createChooser(sendIntent, null)
        context.startActivity(shareIntent)
    }
}
